project: "lab-1"
entity: "reeses"
name: "cnn_E"
method: 'bayes' 

metric: 
  name: 'auc'
  goal: 'maximize'   

parameters:
  preprocessing:
    values: ['None', 'normalizer_max', 'normalizer_l1', 'normalizer_l2', 'minmaxscaler', 'standarizer']
  hidden_size:
    values: [2, 3, 4, 5, 6, 7, 8]
  num_layers:
    min: 1
    max: 5
    distribution: int_uniform
  kernel_size:
    min: 3
    max: 7
    distribution: int_uniform
  stride:
    min: 1
    max: 3
    distribution: int_uniform
  weight:
    values: ['None', 'yes']
  l2:
    min: 0.0
    max: 0.2
    distribution: uniform
